[package]
name = "monitoring"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
proto = { path = "../proto" }
tonic = "0.11.0"
tracing = "0.1"
clap = { version = "4.5", features = ["derive"] }
